INSERT INTO Drinks(`d_id`,`dname`,`p_id`,`alchohol`) VALUES (1,	"fuzzy navel",5,TRUE);
INSERT INTO Drinks(`d_id`,`dname`,`p_id`,`alchohol`) VALUES (2,"martini",4,TRUE);
INSERT INTO Drinks(`d_id`,`dname`,`p_id`,`alchohol`) VALUES (3,"bloody mary", 3,TRUE);
INSERT INTO Drinks(`d_id`,`dname`,`p_id`,`alchohol`) VALUES (4,"margarita",3,TRUE);
INSERT INTO Drinks(`d_id`,`dname`,`p_id`,`alchohol`) VALUES (5,"rum punch",4,TRUE);
INSERT INTO Drinks(`d_id`,`dname`,`p_id`,`alchohol`) VALUES (6,"Mai Tai",5,TRUE);
INSERT INTO Drinks(`d_id`,`dname`,`p_id`,`alchohol`) VALUES (7,"vodka",3,TRUE);
INSERT INTO Drinks(`d_id`,`dname`,`p_id`,`alchohol`) VALUES (8,"beer",2,TRUE);
INSERT INTO Drinks(`d_id`,`dname`,`p_id`,`alchohol`) VALUES (9,"captian morgan",3,TRUE);
INSERT INTO Drinks(`d_id`,`dname`,`p_id`,`alchohol`) VALUES (10,"Spiked Lemondae", 5,TRUE);
INSERT INTO Drinks(`d_id`,`dname`,`p_id`,`alchohol`) VALUES (11,"whiskey",3,TRUE);
INSERT INTO Drinks(`d_id`,`dname`,`p_id`,`alchohol`) VALUES (12,"hurricane", 4, TRUE);
INSERT INTO Drinks(`d_id`,`dname`,`p_id`,`alchohol`) VALUES (13,"bahama mama",4, TRUE);
INSERT INTO Drinks(`d_id`,`dname`,`p_id`,`alchohol`) VALUES (14,"mojitos", 3,TRUE);
INSERT INTO Drinks(`d_id`,`dname`,`p_id`,`alchohol`) VALUES (15,"Rasberry Daiquiri",4, TRUE);
INSERT INTO Drinks(`d_id`,`dname`,`p_id`,`alchohol`) VALUES (16,"Pina Colada", 4, TRUE);
INSERT INTO Drinks(`d_id`,`dname`,`p_id`,`alchohol`) VALUES (17,"fountain drinks", 1, FALSE);
INSERT INTO Drinks(`d_id`,`dname`,`p_id`,`alchohol`) VALUES (18,"water", 0, FALSE);
INSERT INTO Drinks(`d_id`,`dname`,`p_id`,`alchohol`) VALUES (19,"juice", 2, FALSE);
INSERT INTO Drinks(`d_id`,`dname`,`p_id`,`alchohol`) VALUES (20,"smoothie", 3, FALSE);
